### ISSUE TITLE
Getting 200 ok and response with empty list

### ISSUE THREAD

**Issue by mvolz** [zotero/translation-server-old#14]
This link responds with a 200 okay and empty list. http://www.ncbi.nlm.nih.gov/pmc/articles/PMC999999/

Not sure if that's intentional or not, or a problem with translation-server or the translators.

**Comment by dstillman** [comment]
I don't think that's really a translation-server issue. If you browse to that page in Zotero, you can see that it detects a resource on that page but saving doesn't do anything. I don't know if translation-server should do something special in this case, but the current behavior seems at least equivalent to the client's behavior. @adam3smith or @aurimasv can confirm, but I believe the translator should just be tweaked to not detect anything on that page (which it seems like it could do from the page content without waiting for the API response).

**Comment by adam3smith** [comment]
yeah, we'll want to tighten the PMC translator for this, thanks! Feel free to create a ticket in zotero/translators if you'd like an easy way to track this.

**Comment by mvolz** [comment]
I think it would be nice if there was some way for translation-server to indicate this besides the 200, in the way that it has 30x responseCodes for "multiple" responses. If there's a special responseCode for multiple citations on a page it seems logical for it to have one for no citations on the page as well.

**Comment by aurimasv** [comment]
Not importing anything after detect returns a non-false value sounds like
an error to me, so I would expect some sort of error code as well, not
success.

**Comment by dstillman** [comment]
I don't know — most APIs still return 200 for empty result sets. Not sure what the difference is between checking for an empty array and checking for a response code.

But I still don't think this is a translation-server issue, since it's just mirroring the client's behavior. If the client started throwing an error in this case, translation-server would start returning a 500. When the PubMed Central translator is fixed, this will start returning 501 for no translators available.

**Comment by aurimasv** [comment]
I agree that this is an issue with the client. We should be throwing errors in these cases so that they are reported back to zotero.org. I'll have to see if there are cases where that may not be desirable
