### ISSUE TITLE
Update to Zotero 4.0.29.9

### ISSUE THREAD

**Issue by dstillman** [zotero/translation-server-old#19]
https://forums.zotero.org/discussion/58752/

**Comment by zuphilip** [comment]
That would be highly appreciated, see https://github.com/zotero/translators/pull/1066#issuecomment-221977365. For example there are > 2.200 commits since then in the translators. However, it seems better to put them in a separate directory and link accordingly in the `config.js`.

Is the zotero version also connected to the version of XUL Runner one can use? That is also pretty outdated and there is an issue about this here.

**Comment by dstillman** [comment]
> Is the zotero version also connected to the version of XUL Runner one can use?

Yes, I'm updating both.

**Comment by dstillman** [comment]
> there are > 2.200 commits since then in the translators

Note that the translators submodule doesn't matter. It's assumed that people running the server will update translators regularly, either with the built-in `/refresh` endpoint or some other mechanism. (On our servers we update the translators via git and restart the servers twice a day (which gets around memory leak issues too).) A future version might use the client's built-in translator update system for automatic updates, but it's pretty trivial to automate this.

**Comment by zuphilip** [comment]
:sparkles: Thank you for the updates! :sparkles:  I can confirm that the new updated Zotero submodule works with the newest XULRunner.

BTW how do you feel to open the **Wiki** here in the repo for everybody? Then I can try to document things like the `refresh` mechanism, and I think there are more stuff which is currently hidding somewhere in the code...

**Comment by dstillman** [comment]
Not sure there's any reason we need more than the Readme here. Want to start with just a pull request to that?
