### ISSUE TITLE
Local translation-server fails on page

### ISSUE THREAD

**Issue by fbennett** [zotero/translation-server-old#26]
In a local instance of `translation-server`, the test URL from the `README` succeeds, but the following URL fails:

``` bash
http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1664470
```

Exploring further:
- Zotero is able to fetch the item, failing only to acquire a PDF attachment.
- Google Chrome with Zotero connector fetches the item _sans_ PDF to `zotero.org` when Zotero is not running locally.
- The page fails locally, in the same way, with the current `xulrunner`-SDK-based master, and with Konstantin's `firefox`-SDK-based version at https://github.com/kba/translation-server/tree/xulrunner-to-sdk
- The log from a successful run (with Juris-M) is here: [FAILURE.txt](https://github.com/zotero/translation-server/files/298551/FAILURE.txt)
- The log from a failure (with firefox-SDK build) is here: [SUCCESS.txt](https://github.com/zotero/translation-server/files/298552/SUCCESS.txt)

I assume that the grab via the Google Chrome connector invokes a `translation-server` instance at zotero.org. If that's correct, the failure in the local instance is puzzling. On the other hand, I may just be misunderstanding what the GC connector does in the absence of a local Zotero instance, and the page may just not work with `translation-server` full stop.

Any pointers or thoughts very welcome.

**Comment by dstillman** [comment]
The connector still does the translation locally, so that success isn't meaningful, but this does work with the earlier translation-server version. I can replicate the error, so likely just [something else](https://github.com/zotero/translation-server/commit/7636e28378e9f3e372b8bbf17073fa7cdeb4bcaa) sandbox/wrapping-related that needs to be updated for the more recent Firefox versions.

**Comment by dstillman** [comment]
@simonster, any ideas here?

**Comment by zuphilip** [comment]
I can replicate the error as well. My error message points to [line 607 of the Embedded Metadata translator](https://github.com/zotero/translators/blob/master/Embedded%20Metadata.js#L607) which is called inside the SSRN translator:

```
zotero(3)(+0000019): doc.location is null at Embedded Metadata:607

zotero(2)(+0000000): Translate: Translation using Embedded Metadata failed: 
string => TypeError: doc.location is null
stack => addLowQualityMetadata@Embedded Metadata:607
```

If I just comment this line 607 in EM out, then the translation works and the metadata looks good.

The `doc` element in general seems to be there and all the xpath before seem to work. So it is just the `doc.location`. However, we can and maybe should also use the `url` directly in translation.

**Comment by zuphilip** [comment]
Maybe helpful: "If the current document is not in a browsing context, the returned value [of document.location] is `null`." from [MDN doc](https://developer.mozilla.org/de/docs/Web/API/Document/location).

**Comment by zuphilip** [comment]
I tried to analyses this a little bit further and I think the following happens:
- First the SSRN translator is called, more details:
  - [Inside the `processDocuments`-function the `.setDocument(doc)` is performed](https://github.com/zotero/translation-server/blob/master/src/server_translation.js#L218-220)
  - The ["hacked" `processDocuments`](https://github.com/zotero/translation-server/blob/master/src/hacks.js#L73)-function is performing [`onLoad`](https://github.com/zotero/translation-server/blob/master/src/hacks.js#L125-126) which calls a [`wrapDocument(doc)`](https://github.com/zotero/zotero/blob/master/chrome/content/zotero/xpcom/http.js#L998-1008) which defines the necessary context for the document also it does not "live" in the browser.
- The translator starts to do its stuff and [calls the EM translator](https://github.com/zotero/translators/blob/master/SSRN.js#L74-89)
  - No context anymore for document in the EM translator, because we don't use `processDocuments`...

Has someone any ideas how to fix this?

**Comment by zuphilip** [comment]
Okay, I think there are described two errors here (maybe depending on the SDK version used to test it). Both errors are stating that `doc.location` is undefined:
1. @fbennett 's error points to https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/xpcom/translation/translate.js#L1722 which is part of the `.setDocument(doc)` function which is called by any translator which calls another web translator (i.e. mainly EM).
2. My error described above is pointing inside the EM translator and could be fixed by simple rewrite that code. It may also be that after fixing the first error the second will not appear at all.

However, now I also see the first error. What we need is IMO to wrap the `doc` before calling `.setTranslator(doc)` and thereby make sure that `doc.location` is defined with the also need the url. Therefore I would like to try to modify the `doWeb` function, which is called here https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/xpcom/translation/translate.js#L1222. In this function call we use the `_getParameters` function see https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/xpcom/translation/translate.js#L1776-L1785. This looks like the right place to do another wrap. This are just 10 lines but I don't understand these lines enough to change anything here. Any advice?

**Comment by zuphilip** [comment]
How about something like to replace https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/xpcom/translation/translate.js#L1782-L1784 with

``` javascript
    else {
        if (!this.document.location) {//this occurs in translation-server
            this.document = Zotero.HTTP.wrapDocument(this.document, this.location);
        }
        return [this.document, this.location];
    }
```

:question:

**Comment by zuphilip** [comment]
Okay, here is a fix. Change the translator SSRN.js as follows:

``` diff
diff --git a/SSRN.js b/SSRN.js
index 1273381..17aba4b 100644
--- a/SSRN.js
+++ b/SSRN.js
@@ -74,7 +74,7 @@ function scrape(doc, url) {
        // We call the Embedded Metadata translator to do the actual work
        var translator = Zotero.loadTranslator("web");
        translator.setTranslator("951c027d-74ac-47d4-a107-9c3069ab7b48");
-       translator.setDocument(doc);
+       //translator.setDocument(doc);
        translator.setHandler("itemDone", function(obj, item) {
                item.itemType = "report";
                item.type = "SSRN Scholarly Paper";
@@ -86,7 +86,11 @@ function scrape(doc, url) {

                item.complete();
        });
-       translator.translate();
+       //translator.translate();
+       translator.getTranslatorObject(function(trans) {
+               trans.doWeb(doc, url);
+       });
+
 }
 /** BEGIN TEST CASES **/
 var testCases = [
@@ -162,4 +166,4 @@ var testCases = [
                ]
        }
 ]
-/** END TEST CASES **/
\ No newline at end of file
+/** END TEST CASES **/
```

This works for me with XULRunner 41.0.2. Can someone confirm that?
