### ISSUE TITLE
Save generic webpages

### ISSUE THREAD

**Issue by dstillman** [zotero/translation-server-old#32]
Instead of returning 501 when no translators, the server should just follow the client and return title, URL, and access date.

It occurred to me that this could be implemented as a translator, so the same fallback code didn't have to be added anywhere that used translators, but I suspect that would result in just as much special-casing — to show the gray icon in the client, <s>to avoid showing 'multiple' on every page,</s> etc.

Another option would be to rename "Embedded Metadata" to "Webpage" and do the final fallback in that, but even in the single-save-button era I still think there's value in setting different expectations for EM and &lt;title/&gt;.

**Comment by zuphilip** [comment]
If multiple translator are available for a site, then one can choose between them in the local client. Personally, I use for example the EM or website translator for sites, that I want to read later offline. On the other hand when I am saving references in Zotero for a future bibliography, I choose the best translator. I exclude often the doi translator, because the dois in the website may be just a reference for an article mentioned somewhere in the text.

The translation server will only provide the best translator available for a website. In the use cases I can imagine for translation server this seems okay. However, I could imagine that someone might wish to exclude a certain translator, but this can also been achieved by using an adjusted translator directory.

<blockquote>Another option would be to rename "Embedded Metadata" to "Webpage" and do the final fallback in that, but even in the single-save-button era I still think there's value in setting different expectations for EM and &lt;title/&gt;.</blockquote>

My first reaction was also to say, that we should be able to distinguish between data from "Embedded Metadata" translator or "Webpage" extraction. However, I am not that sure anymore. CC @adam3smith Why should we distinguish these two? I cannot imagine any use case for that. We could also name it to something like "Website Data" or "Web Data". It would be important to attach always a snapshot, but I think EM is already doing that at the moment.

Extending EM translator one thing, but I don't know how much code in the zotero client might be changed for the grey icon and if we still want two options with and without snapshot...

**Comment by dstillman** [comment]
Sorry, the 'multiple' thing was nonsense, obviously — 'multiple' != priority. So that, at least, wouldn't be an issue. Would still need to check the id of the highest-priority translator and show gray icon if Webpage. Might be some other tweaks necessary.

> Why should we distinguish these two? I cannot imagine any use case for that.

It's just that it conveys quickly that Zotero is able to do something special on certain pages, which serves a marketing purpose as much as anything else. Zotero is more than a bookmark tool. This, for years, was one reason we separated the two buttons — we thought it was important to show when Zotero could work its magic. Even though we now only have one button, I think that still applies.

From a practical standpoint, while you need to check all data if you're planning to cite things, when the icon is gray you know immediately that you only have the page title and nothing else and should fill in the other details if you need them (as was the case with "Create Web Page Item from Current Page" before).

**Comment by zuphilip** [comment]
**Visual appearance of Zotero icon**: I can follow your argumentation that the save website and (richer) translator extraction should be visually distinguish in the Zotero client/browser. There are two things changing here: the icon for webpage is simpler, and the icon is grayed out if there is only the website save. Is there any reason that the save website is colorful in the cases that there are other translator options available?

**Seperate options for EM and website save**: That is what I was referring to above: "Why should we distinguish these two? I cannot imagine any use case for that." i.e. I cannot imagine using a website save option when the EM translator is present. This supports your proposal to merge the save website option into EM translator.

**Comment by dstillman** [comment]
This should still be implemented as a generic translator, but for now this is taken care of by https://github.com/zotero/translation-server/commit/410245177bd90f4ee6f0c43917b5b6c96b63887d.
