### ISSUE TITLE
Error: Invalid Host header

### ISSUE THREAD

**Issue by zuphilip** [zotero/translation-server-old#48]
I build the a [docker container](https://hub.docker.com/r/zuphilip/translation-server/builds/) with the newest changes and run it locally with `$ docker run --rm -p 1969:1969 --name translation-server-container zuphilip/translation-server`. Everything seems to build but the examples are not working, e.g.
```
$ curl -d '{"url":"http://www.tandfonline.com/doi/abs/10.1080/15424060903167229","sessionid":"abc123"}'        --header "Content-Type: application/json"        127.0.0.1:1969/web

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   111    0    20  100    91     20     91  0:00:01 --:--:--  0:00:01 91000Invalid Host header
```

**Comment by AndrewIsh** [comment]
Can confirm, I updated to the latest changes just now and am now getting:
```
zotero(3)(+0000189): HTTP server listening on *:1969

zotero(5)(+0018416): POST /import HTTP/1.1
cache-control: no-cache
Postman-Token: b3f7bad1-7562-476e-867e-06fa07b4526b
Content-Type: application/json
User-Agent: PostmanRuntime/6.1.6
Accept: */*
Host: localhost:1969
accept-encoding: gzip, deflate
content-length: 726
Connection: keep-alive



zotero(5)(+0000001): HTTP/1.0 400 Bad Request
Content-Type: text/plain

Invalid Host header
```

**Comment by AndrewIsh** [comment]
Looking in the source, in zotero-connectors, I notice that there's a check that `Host` is `127.0.0.1`, I was sending `localhost`. Manually changing the `Host` header to `127.0.0.1` in Postman fixed the problem. Changing the `Host` header is not possible in client-side code.

The reason for using `127.0.0.1` is given as a preventative measure against DNS rebinding attacks. In which case, adding `localhost` to the regex shouldn't be a problem, should it?

I'll add an issue to zotero-connectors to add `localhost`.

**Comment by AndrewIsh** [comment]
Many thanks for the update, but I'm seeing additional problems to do with this header check. I realise the root of the symptom I'm seeing comes from the Host regex in the Zotero code, but since you modified the regex above I assume you're happy to patch locally before an upstream fix appears?

I've now installed the translation-server on a production server. Doing some tests both from my browser and Postman, I've noticed that the following Host header is being received (and rejected):

`Host: <my-domain>:8080` (where `my-domain` is the fully qualified domain name that the request was sent to).

This is being failed by the same regex as before.

I think possibly the best way to fix this is to add a pref to `config.js` where the user specifies the domain on which the translation-server is being hosted and, by implication, the domain from which requests will be coming, this could then be checked by the regex. This would not compromise the DNS rebinding protection.

**Comment by dstillman** [comment]
We'll just disable the header check in translation-server, since it's not relevant there.

(Note that, while bug reports are definitely appreciated, the recommended version of translation-server for production use is the one on Docker Hub, not the latest version in git. We're still testing and fixing things after upgrading it to the 5.0 codebase.)

**Comment by dstillman** [comment]
(I'll also update the README, since I realize that says to build from git. What's there now predates our publishing a version to Docker Hub.)

**Comment by AndrewIsh** [comment]
Many thanks for this info. I would install from Docker Hub but I assume I would then suffer from the csl-json import/export problem that existed prior to the recent update. In which case, I'll stick with Github until the version on Docker Hub is updated. Many thanks for the heads up though :)

**Comment by zuphilip** [comment]
> We'll just disable the header check in translation-server, since it's not relevant there.

This sounds good, because I for example have to use the docker-machine ip on my windows 7 machine here with Docker Toolbox.
